use_frameworks!

target 'dramacommon_Example' do
  pod 'dramacommon', :path => '../'

  target 'dramacommon_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
